[A1] No failure event was generated for +!init[source(self)]
